# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-10 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('designation', models.CharField(max_length=122)),
                ('img', models.ImageField(upload_to='uploaded_imgs')),
                ('status', models.IntegerField(default=1)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
    ]
