# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-13 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_teams_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_custom_sql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='teamcrud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('designation', models.CharField(max_length=122)),
                ('img', models.ImageField(upload_to='uploaded_imgs')),
                ('status', models.IntegerField(default=1)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'home_teams',
            },
        ),
    ]
